databases:
  - name: trading_app
    databaseName: trading_app
    user: trading_app
    plan: free

services:
  - type: web
    name: trading_app
    runtime: ruby
    plan: free
    buildCommand: "bin/render-build.sh"
      # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trading_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
